# Generated by Django 4.1.1 on 2022-10-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starships', '0004_alter_starship_max_passengers_alter_starship_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='starship',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='starship',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
