# Generated by Django 4.1 on 2022-08-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starship',
            old_name='passengers',
            new_name='max_passengers',
        ),
    ]
