# Generated by Django 4.1 on 2022-08-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starships', '0002_rename_passengers_starship_max_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starship',
            name='max_passengers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='starship',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
